### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by ghost** [gamax92/GXCraft#2]
Did this ever compile?  Is there a dol file?

**Comment by gamax92** [comment]
Yeah this does compile, I've been very on/off about this project, but have a dol.
[GXCraft.zip](https://github.com/gamax92/GXCraft/files/549433/GXCraft.zip)
(Built 2016-10-24)

**Comment by ghost** [comment]
cool, runs very well on the wii.  I can't move up or down and there is no collision detection but it runs at 60fps which is an epic achievement.   Too bad the wii homebrew scene has died out.  this is the best clone I have seen so far (out of about 3) - this should have been out in 2010 when the wii was hot stuff.  One clone was released just last week but with far less features than yours ( https://github.com/DaeFennek/wii-voxel-engine ).  good work on what you have achieved so far.  all the best.

**Comment by gamax92** [comment]
Moving up and down should just be [+] and [-] buttons on the Wii Remote, just make sure you're not in inventory mode, toggled by [1] and also indicated by the hotbar selection lighting up and dimming

**Comment by ghost** [comment]
yes, I understand it now.  not very obvious.

**Comment by ghost** [comment]
Oh, I see how it works now.

**Comment by gamax92** [comment]
I mean, if you read the controls listed in the readme, it says all of the same stuff I told you.

Anyway, as far as binaries, not right now, the Wii scene is basically dead and I don't care about this project as much as I did a few years ago.
