### ISSUE TITLE
Terrain fails to render when using devkitppc r28 or newer.

### ISSUE THREAD

**Issue by gamax92** [gamax92/GXCraft#3]
For whatever reason, compiling this repository with devkitppc r28 or newer results in nothing getting drawn to the screen except for the hotbar and debug text. Replacing the `devkitPPC/powerpc-eabi/bin/ld` binary with the one from r27 makes the issue go away, but this is a workaround and not a fix.

No leads, any help would be appreciated.

**Comment by gamax92** [comment]
Some change in binutils from 2.24 to 2.25 causes this issue to appear.

**Comment by ghost** [comment]
Hmmmm I wonder if its c++ related?   I am just guessing

**Comment by gamax92** [comment]
After performing a bisect against binutils, I've come across this commit being the one that causes the issue.

[93d1b056cb396d6468781fe0e40dd769891bed32](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=93d1b056cb396d6468781fe0e40dd769891bed32)

**Comment by gamax92** [comment]
Not at all fixed, making new changes to the code and the issue reappears again.

**Comment by gamax92** [comment]
No longer an issue
