### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by WiseMatthack** [gamax92/GXCraft#4]
There are not all the files in the repo, so compilation is impossible.
Would it be possible to add a compiled version of the project to the repo? I really want to test it, it looks very cool!

**Comment by gamax92** [comment]
There was a script called `regen_textures.sh` that needed to be ran before compilation, but I have now included texture handling in the Makefile so building is straight forward now.

**Comment by WiseMatthack** [comment]
absolutely fantastic! thanks a lot!
would it be possible to include a binary so that people who don't have a lot of knowledge can enjoy it too?

**Comment by gamax92** [comment]
I could see about setting up some kind of CI automatic build at some point.
